# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries

name: base

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

dependencies:
  # --------- pytorch --------- #
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - lightning>=2.0.0
  - torchmetrics>=0.11.4
  - cutlass

    # --------- config and tests--------- #
  - hydra-core
  - rich
  - pre-commit
  - pytest

  # --------- loggers --------- #
  - wandb

  - pip>=23
  - pip:
      - sh
      - packaging
      - ninja
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
      - triton
      - flash-attn --no-build-isolation
      - git+https://github.com/mlcommons/logging.git
      - huggingface_hub